### PR TITLE
Relevant rows generation

### PR DESCRIPTION
**Pull request by zaibacu**
-  Allow to generate by concrete data instead of row number
- Initial barebones for UI integration testing. Process is there, but lacking actual tests

### CODE REVIEW

**Comment by zaibacu** [comment]
Initial row seems to be ignored, working on it

**Comment by rokasramas** [comment]
Screenshot from 2021-03-05 16-22-18
Something is not right, to reproduce this, upload two files, switch rows, select another file. In this case, files have similarly named columns, and as you see generation is using data from another file.
It would also be nice if "First 20" was first selection by display order, and keep it selected by default.

**Review by rokasramas — CHANGES_REQUESTED** [review]
Seems to be working ok now, just last thing - "First 20" should come before "Most relevant":
Screenshot from 2021-03-25 10-41-18

**Review by rokasramas — CHANGES_REQUESTED** [review]
After creating new document plan "First 20" switches to "Most relevant"

**Review by rokasramas — APPROVED** [review]

**Pull request merged**
